version: '3'

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mapping_service
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/root/redis
    environment:
      REDIS_PASSWORD: redis

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TZ="Europe/Moscow"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootrootroot
    command: server --console-address ":9001" /data

  auth-service:
    build: auth-service/
    container_name: auth-service
    ports:
      - "81:8080"
      - "5006:5005"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: mapping_service
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      ACCESS_TTL: 600
      REFRESH_TTL: 864000
    depends_on:
      - database
      - redis
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
  user-service:
    build: user-service/
    container_name: user-service
    ports:
      - "82:8080"
      - "5007:5005"
    environment:
      AUTH_SERVICE_HOST: auth-service
      AUTH_SERVICE_PATH: auth
      AUTH_SERVICE_PORT: 8080
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: mapping_service
      DB_USER: postgres
      DB_PASSWORD: postgres
      MINIO_HOST: minio
      MINIO_LOGIN: root
      MINIO_PASSWORD: rootrootroot
      MINIO_PORT: 9000
      MINIO_BUCKET_NAME: avatars
    depends_on:
      auth-service:
        condition: service_healthy
      minio:
        condition: service_started
      database:
        condition: service_started
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  database: {}
  redis: {}
  minio_storage: {}